name: riverpod_e_commerce
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  #packages
  cupertino_icons: ^1.0.8
  #state management
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  #state management helper
  equatable: ^2.0.5
  #local storage packages
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.2.2
  #responsive
  flutter_screenutil: ^5.9.3
  #helper
  url_launcher: ^6.3.0
  intl: ^0.19.0
  file_picker: ^8.1.2
  #ui
  flutter_rating_bar: ^4.0.1
  lottie: ^3.1.3
  skeletonizer: ^1.4.2
  flutter_swiper_plus: ^2.0.4
  flutter_html: ^3.0.0-beta.2
  shimmer: ^3.0.0
  photo_view: ^0.15.0
  dotted_border: ^2.1.0
  cherry_toast: ^1.10.0
  dynamic_height_grid_view: ^0.0.4
  cached_network_image: ^3.4.1
  dropdown_button2: ^2.1.4
  flutter_svg: ^2.0.11
  #secure
  flutter_dotenv: ^5.1.0
  #supabase
  supabase_flutter: ^2.8.2
  #firebase
  firebase_core: ^3.10.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  #assets
  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/
    - assets/fonts/poppins/
    - assets/fonts/tajwal/
    - .env


  fonts:
  - family: tajwal
    fonts:
        - asset: assets/fonts/tajwal/Tajawal-Regular.ttf
        - asset: assets/fonts/tajwal/Tajawal-Bold.ttf
        - asset: assets/fonts/tajwal/Tajawal-Black.ttf
        - asset: assets/fonts/tajwal/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/tajwal/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/tajwal/Tajawal-Light.ttf
        - asset: assets/fonts/tajwal/Tajawal-Medium.ttf

  - family: poppins
    fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
